# Generated by Django 5.2.11 on 2026-03-08 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('portions', 'Portions'), ('kg', 'kg'), ('litres', 'Litres'), ('packets', 'Packets'), ('boxes', 'Boxes')], default='portions', max_length=20)),
                ('prepared_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('location', models.TextField()),
                ('pickup_available', models.BooleanField(default=True)),
                ('delivery_mode', models.CharField(choices=[('platform', 'Platform'), ('self', 'Self Delivery')], default='platform', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_listings', to=settings.AUTH_USER_MODEL)),
                ('delivery_guy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
